/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/main/webapp/app/entities/produto/produto.service';
import * as i1 from '@angular/http';
export function ProdutoServiceNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.ProdutoService,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Http}}}],
      lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9lbnRpdGllcy9wcm9kdXRvL3Byb2R1dG8uc2VydmljZS5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21mZXJuYW5kZXMvZXJlc3RhdXJhbnRlL3NyYy9tYWluL3dlYmFwcC9hcHAvZW50aXRpZXMvcHJvZHV0by9wcm9kdXRvLnNlcnZpY2UudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OyJ9
