/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/main/webapp/app/entities/produto/produto-dialog.component';
import * as i1 from '@ng-bootstrap/ng-bootstrap/modal/modal-ref';
import * as i2 from 'ng-jhipster/src/service/data-util.service';
import * as i3 from 'ng-jhipster/src/service/alert.service';
import * as i4 from '../../../../../../../../src/main/webapp/app/entities/produto/produto.service';
import * as i5 from '../../../../../../../../src/main/webapp/app/entities/imposto/imposto.service';
import * as i6 from '@angular/core';
import * as i7 from 'ng-jhipster/src/service/event-manager.service';
import * as i8 from '../../../../../../../../src/main/webapp/app/entities/impressora/impressora.service';
import * as i9 from './produto-dialog.component.ngfactory';
import * as i10 from '@angular/router';
import * as i11 from '../../../../../../../../src/main/webapp/app/entities/produto/produto-popup.service';
export function ProdutoDialogComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ProdutoDialogComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.NgbActiveModal}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.JhiDataUtils}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.JhiAlertService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.ProdutoService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.ImpostoService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i6.ElementRef}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i7.JhiEventManager}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i8.ImpressoraService}}}],lifecycleHooks:[0]},
      isComponent:true,selector:'jhi-produto-dialog',exportAs:(null as any),inputs:{},
      outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i9.View_ProdutoDialogComponent_0,
      rendererType:i9.RenderType_ProdutoDialogComponent,componentFactory:i9.ProdutoDialogComponentNgFactory}];
}
export function ProdutoPopupComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ProdutoPopupComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i10.ActivatedRoute}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i11.ProdutoPopupService}}}],lifecycleHooks:[0,
      1]},isComponent:true,selector:'jhi-produto-popup',exportAs:(null as any),inputs:{},
      outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i9.View_ProdutoPopupComponent_0,
      rendererType:i9.RenderType_ProdutoPopupComponent,componentFactory:i9.ProdutoPopupComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9lbnRpdGllcy9wcm9kdXRvL3Byb2R1dG8tZGlhbG9nLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21mZXJuYW5kZXMvZXJlc3RhdXJhbnRlL3NyYy9tYWluL3dlYmFwcC9hcHAvZW50aXRpZXMvcHJvZHV0by9wcm9kdXRvLWRpYWxvZy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
