/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/main/webapp/app/entities/impressora/impressora.component';
import * as i1 from '../../../../../../../../src/main/webapp/app/entities/impressora/impressora.service';
import * as i2 from 'ng-jhipster/src/service/alert.service';
import * as i3 from 'ng-jhipster/src/service/data-util.service';
import * as i4 from 'ng-jhipster/src/service/event-manager.service';
import * as i5 from '../../../../../../../../src/main/webapp/app/shared/auth/principal.service';
import * as i6 from './impressora.component.ngfactory';
export function ImpressoraComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ImpressoraComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ImpressoraService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.JhiAlertService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.JhiDataUtils}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.JhiEventManager}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Principal}}}],
      lifecycleHooks:[0,1]},isComponent:true,selector:'jhi-impressora',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i6.View_ImpressoraComponent_0,
      rendererType:i6.RenderType_ImpressoraComponent,componentFactory:i6.ImpressoraComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9lbnRpdGllcy9pbXByZXNzb3JhL2ltcHJlc3NvcmEuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9lbnRpdGllcy9pbXByZXNzb3JhL2ltcHJlc3NvcmEuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
