/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/main/webapp/app/entities/impressora/impressora-detail.component';
import * as i1 from 'ng-jhipster/src/service/event-manager.service';
import * as i2 from 'ng-jhipster/src/service/data-util.service';
import * as i3 from '../../../../../../../../src/main/webapp/app/entities/impressora/impressora.service';
import * as i4 from '@angular/router';
import * as i5 from './impressora-detail.component.ngfactory';
export function ImpressoraDetailComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ImpressoraDetailComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.JhiEventManager}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.JhiDataUtils}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.ImpressoraService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.ActivatedRoute}}}],lifecycleHooks:[0,1]},
      isComponent:true,selector:'jhi-impressora-detail',exportAs:(null as any),inputs:{},
      outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i5.View_ImpressoraDetailComponent_0,
      rendererType:i5.RenderType_ImpressoraDetailComponent,componentFactory:i5.ImpressoraDetailComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9lbnRpdGllcy9pbXByZXNzb3JhL2ltcHJlc3NvcmEtZGV0YWlsLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21mZXJuYW5kZXMvZXJlc3RhdXJhbnRlL3NyYy9tYWluL3dlYmFwcC9hcHAvZW50aXRpZXMvaW1wcmVzc29yYS9pbXByZXNzb3JhLWRldGFpbC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
