/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/main/webapp/app/entities/venda/venda-dialog.component';
import * as i1 from '@ng-bootstrap/ng-bootstrap/modal/modal-ref';
import * as i2 from 'ng-jhipster/src/service/alert.service';
import * as i3 from '../../../../../../../../src/main/webapp/app/entities/venda/venda.service';
import * as i4 from '../../../../../../../../src/main/webapp/app/entities/produto/produto.service';
import * as i5 from '../../../../../../../../src/main/webapp/app/entities/comanda/comanda.service';
import * as i6 from 'ng-jhipster/src/service/event-manager.service';
import * as i7 from './venda-dialog.component.ngfactory';
import * as i8 from '@angular/router';
import * as i9 from '../../../../../../../../src/main/webapp/app/entities/venda/venda-popup.service';
export function VendaDialogComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.VendaDialogComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.NgbActiveModal}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.JhiAlertService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.VendaService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.ProdutoService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.ComandaService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i6.JhiEventManager}}}],lifecycleHooks:[0]},
      isComponent:true,selector:'jhi-venda-dialog',exportAs:(null as any),inputs:{},
      outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i7.View_VendaDialogComponent_0,
      rendererType:i7.RenderType_VendaDialogComponent,componentFactory:i7.VendaDialogComponentNgFactory}];
}
export function VendaPopupComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.VendaPopupComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i8.ActivatedRoute}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i9.VendaPopupService}}}],lifecycleHooks:[0,
      1]},isComponent:true,selector:'jhi-venda-popup',exportAs:(null as any),inputs:{},
      outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i7.View_VendaPopupComponent_0,
      rendererType:i7.RenderType_VendaPopupComponent,componentFactory:i7.VendaPopupComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9lbnRpdGllcy92ZW5kYS92ZW5kYS1kaWFsb2cuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9lbnRpdGllcy92ZW5kYS92ZW5kYS1kaWFsb2cuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
