/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/main/webapp/app/shared/utils/IncrementoPipe.pipe';
export function IncrementoPipeNgSummary():any[] {
  return [{summaryKind:0,type:{reference:i0.IncrementoPipe,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
      name:'incremento',pure:true}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9zaGFyZWQvdXRpbHMvSW5jcmVtZW50b1BpcGUucGlwZS5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21mZXJuYW5kZXMvZXJlc3RhdXJhbnRlL3NyYy9tYWluL3dlYmFwcC9hcHAvc2hhcmVkL3V0aWxzL0luY3JlbWVudG9QaXBlLnBpcGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7OzsifQ==
