/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/main/webapp/app/shared/utils/variaveis.service';
import * as i1 from 'ng2-webstorage/dist/services/localStorage';
import * as i2 from '../../../../../../../../src/main/webapp/app/entities/mesa/mesa.service';
import * as i3 from '../../../../../../../../src/main/webapp/app/entities/comanda/comanda.service';
export function VariaveisServiceNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.VariaveisService,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.LocalStorageService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.MesaService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.ComandaService}}}],
      lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9zaGFyZWQvdXRpbHMvdmFyaWF2ZWlzLnNlcnZpY2UubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9tZmVybmFuZGVzL2VyZXN0YXVyYW50ZS9zcmMvbWFpbi93ZWJhcHAvYXBwL3NoYXJlZC91dGlscy92YXJpYXZlaXMuc2VydmljZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
