/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/main/webapp/app/shared/auth/user-route-access-service';
import * as i1 from '@angular/router';
import * as i2 from '../../../../../../../../src/main/webapp/app/shared/login/login-modal.service';
import * as i3 from '../../../../../../../../src/main/webapp/app/shared/auth/principal.service';
import * as i4 from '../../../../../../../../src/main/webapp/app/shared/auth/state-storage.service';
import * as i5 from '../../../../../../../../src/main/webapp/app/shared/login/autologin.service';
export function UserRouteAccessServiceNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.UserRouteAccessService,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Router}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.LoginModalService}}},{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.Principal}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.StateStorageService}}},{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.AutologinService}}}],
      lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9zaGFyZWQvYXV0aC91c2VyLXJvdXRlLWFjY2Vzcy1zZXJ2aWNlLm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9zaGFyZWQvYXV0aC91c2VyLXJvdXRlLWFjY2Vzcy1zZXJ2aWNlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
