/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../node_modules/ng-jhipster/src/language/jhi-translate.directive.ngfactory';
import * as i2 from 'ng-jhipster/src/language/jhi-translate.directive';
import * as i3 from '../../../../../../../../src/main/webapp/app/layouts/error/error.component';
import * as i4 from '@angular/router';
import * as i5 from '../../../../../../../../src/main/webapp/app/shared/login/autologin.service';
const styles_ErrorComponent:any[] = ([] as any[]);
export const RenderType_ErrorComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ErrorComponent,data:{}});
export function View_ErrorComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),26,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),[' '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      23,'div',[['class','row']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),[' '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),3,'div',[['class','col-md-4']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),[' '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),0,'span',[['class','hipster img-fluid rounded']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),[' '])),(_l()(),i0.ɵted((null as any),[' '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),15,'div',[['class','col-md-8']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),[' '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          2,'h1',[['jhiTranslate','error.title']],(null as any),(null as any),(null as any),
          i1.View_JhiTranslateComponent_0,i1.RenderType_JhiTranslateComponent)),i0.ɵdid(49152,
          (null as any),0,i2.JhiTranslateComponent,([] as any[]),{jhiTranslate:[0,
              'jhiTranslate']},(null as any)),(_l()(),i0.ɵted((null as any),['Error Page!'])),
      (_l()(),i0.ɵted((null as any),[' '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'div',([] as any[]),[[8,'hidden',0]],(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),[' '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'div',[['class','alert alert-danger']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['',' '])),(_l()(),i0.ɵted((null as any),[' '])),(_l()(),i0.ɵted((null as any),
          [' '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'div',[['class',
          'alert alert-danger'],['jhiTranslate','error.http.403']],[[8,'hidden',0]],
          (null as any),(null as any),i1.View_JhiTranslateComponent_0,i1.RenderType_JhiTranslateComponent)),
      i0.ɵdid(49152,(null as any),0,i2.JhiTranslateComponent,([] as any[]),{jhiTranslate:[0,
          'jhiTranslate']},(null as any)),(_l()(),i0.ɵted((null as any),['You are not authorized to access this page. '])),
      (_l()(),i0.ɵted((null as any),[' '])),(_l()(),i0.ɵted((null as any),[' '])),
      (_l()(),i0.ɵted((null as any),[' '])),(_l()(),i0.ɵted((null as any),[' ']))],
      (_ck,_v) => {
        const currVal_0:any = 'error.title';
        _ck(_v,12,0,currVal_0);
        const currVal_4:any = 'error.http.403';
        _ck(_v,22,0,currVal_4);
      },(_ck,_v) => {
        var _co:i3.ErrorComponent = _v.component;
        const currVal_1:boolean = !_co.errorMessage;
        _ck(_v,15,0,currVal_1);
        const currVal_2:any = _co.errorMessage;
        _ck(_v,18,0,currVal_2);
        const currVal_3:boolean = !_co.error403;
        _ck(_v,21,0,currVal_3);
      });
}
export function View_ErrorComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'jhi-error',([] as any[]),
      (null as any),(null as any),(null as any),View_ErrorComponent_0,RenderType_ErrorComponent)),
      i0.ɵdid(114688,(null as any),0,i3.ErrorComponent,[i4.ActivatedRoute,i5.AutologinService],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ErrorComponentNgFactory:i0.ComponentFactory<i3.ErrorComponent> = i0.ɵccf('jhi-error',
    i3.ErrorComponent,View_ErrorComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9sYXlvdXRzL2Vycm9yL2Vycm9yLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21mZXJuYW5kZXMvZXJlc3RhdXJhbnRlL3NyYy9tYWluL3dlYmFwcC9hcHAvbGF5b3V0cy9lcnJvci9lcnJvci5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL21mZXJuYW5kZXMvZXJlc3RhdXJhbnRlL3NyYy9tYWluL3dlYmFwcC9hcHAvbGF5b3V0cy9lcnJvci9lcnJvci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvbWZlcm5hbmRlcy9lcmVzdGF1cmFudGUvc3JjL21haW4vd2ViYXBwL2FwcC9sYXlvdXRzL2Vycm9yL2Vycm9yLmNvbXBvbmVudC50cy5FcnJvckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+IDxkaXYgY2xhc3M9XCJyb3dcIj4gPGRpdiBjbGFzcz1cImNvbC1tZC00XCI+IDxzcGFuIGNsYXNzPVwiaGlwc3RlciBpbWctZmx1aWQgcm91bmRlZFwiPjwvc3Bhbj4gPC9kaXY+IDxkaXYgY2xhc3M9XCJjb2wtbWQtOFwiPiA8aDEgamhpVHJhbnNsYXRlPVwiZXJyb3IudGl0bGVcIj5FcnJvciBQYWdlITwvaDE+IDxkaXYgW2hpZGRlbl09XCIhZXJyb3JNZXNzYWdlXCI+IDxkaXYgY2xhc3M9XCJhbGVydCBhbGVydC1kYW5nZXJcIj57e2Vycm9yTWVzc2FnZX19IDwvZGl2PiA8L2Rpdj4gPGRpdiBbaGlkZGVuXT1cIiFlcnJvcjQwM1wiIGNsYXNzPVwiYWxlcnQgYWxlcnQtZGFuZ2VyXCIgamhpVHJhbnNsYXRlPVwiZXJyb3IuaHR0cC40MDNcIj5Zb3UgYXJlIG5vdCBhdXRob3JpemVkIHRvIGFjY2VzcyB0aGlzIHBhZ2UuIDwvZGl2PiA8L2Rpdj4gPC9kaXY+IDwvZGl2PiAiLCI8amhpLWVycm9yPjwvamhpLWVycm9yPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFLO2FBQUEsdUJBQUM7TUFBQTtNQUFBLGdCQUFpQixzQ0FBQztNQUFBO01BQUEsOEJBQXNCLHNDQUFDO2FBQUE7VUFBQTtNQUErQyxzQ0FBTztNQUFDO1VBQUE7TUFBc0Isc0NBQUM7VUFBQTs2RUFBQSxVQUFBO1VBQUE7Y0FBQSxnQ0FBK0I7TUFBZ0Isc0NBQUM7VUFBQTtVQUFBLGdCQUE4QixzQ0FBQztVQUFBO1VBQUEsMERBQWdDO1VBQUEsV0FBdUIsc0NBQU87VUFBQSxRQUFDO1VBQUE7VUFBQTthQUFBO1VBQUEsZ0NBQW1GO01BQWtELHNDQUFPO01BQU8sc0NBQU87O1FBQXBTO1FBQUosWUFBSSxTQUFKO1FBQW1NO1FBQXJELFlBQXFELFNBQXJEOzs7UUFBekY7UUFBTCxZQUFLLFNBQUw7UUFBK0Q7UUFBQTtRQUFvQztRQUFMLFlBQUssU0FBTDs7OztvQkNBM1E7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
